name: Build RS Browser

on: v1

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get SHA256 Fingerprint
        # Isse logs mein aapko fingerprint mil jayegi assetlinks.json ke liye
        run: ./gradlew signingReport

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Rename and Move APK
        run: |
          mkdir -p build-output
          # Poore project folder mein APK dhoond kar move karega
          find . -name "*.apk" -type f -exec cp {} build-output/RS-Browser-v2.apk \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RS-Browser-Package-v2
          path: build-output/RS-Browser-v2.apk

