name: Build RS Browser
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        run: ./gradlew signingReport

      - name: Rename and Move APK
        run: |
          mkdir -p build-output
          # Yeh command poore project mein APK dhoond kar rename karegi
          find app/build/outputs/apk/ -name "*.apk" -exec cp {} build-output/RS-Browser-v1.apk \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RS-Browser-Package
          path: build-output/RS-Browser-v3.apk
